<?php
/**
 * @author      Oleh Kravets <oleh.kravets@snk.de>
 * @copyright   Copyright (c) 2020 schoene neue kinder GmbH  (https://www.snk.de)
 * @license     https://opensource.org/licenses/MIT          MIT License
 */
/**
 * @var $block \Snk\Usercentrics\Block\UsercentricsJs
 */
?>
<script type="application/javascript"
        src="<?= $block->escapeUrl($block->getScriptUrl()) ?>"
        id="<?= $block->escapeHtmlAttr($block->getSettingsId()) ?>">
</script>
